### Connexion
POST http://localhost:8000/api/login_check
content-type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Liste des favoris
GET http://localhost:8000/api/favorite/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDQzNjM0NjgsImV4cCI6MTcwNDM2NzA2OCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6Im1haWFuYSJ9.M-ZsKY17BxynYwBidc2Zeh2UfnpSxjYXYsCFAoVhVkT_Mj14eW-JW-2rgjbC1VaRXm84xKuk_PNR7Ggf1cJEof7YvCAQuCsiu-C4Muf5itMQOEreII1A_ZxEmAzZ6yo22ROkmogzm0RrQRbq0x4VDyF1s0_TLd44nt1OLumxHbI9KJqgyJW0jiXI9E1WGFaiEIvkcthYGTmgSjDJgT65v8rN6dYe7kNqyoE-863lCjGs4yLigHFa-Hp_1uSVMYrwLFcMGpHkNe0K6xP4-V4MbQq3S7OpFHXZ3SXi4WpTsDMg_rLnnru-mrzVsOthj-NhOK1ZzzB7FDwo_xG94cCXBdRkBQpCQZaTD8rU8A7Kw48MRaBiwI9PhxvkellE_MF5tNVNH0BNjxT_msnrrvBZA1bgXSorY4BG1CjGI25k_msBLt805V2AApMq6PTftBLLpxw50jZLpQiJOh34UoRPUcon70auhS2pWoD7vexhbdd0MYXo4y4KfRN_3_cqcQt7j87TQjzgWE-02QA9hAXICCWwqRkmzDivOXSfiKFpM4ITJKAAG0vqKeZctwF4SEc6FvUUuma0Y8YMJSvvm64I-dYkNRVtOq-SgS3LzA-C7azm9iPlsdN_ZSOKCTmH1KWI9vUazpnQKvISV6Xgj70XT8hVNyowl9oVIcSlvDttBKM

### Suppression d'un favoris
DELETE http://localhost:8000/api/favorite/delete/6
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDQzNjM0NjgsImV4cCI6MTcwNDM2NzA2OCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6Im1haWFuYSJ9.M-ZsKY17BxynYwBidc2Zeh2UfnpSxjYXYsCFAoVhVkT_Mj14eW-JW-2rgjbC1VaRXm84xKuk_PNR7Ggf1cJEof7YvCAQuCsiu-C4Muf5itMQOEreII1A_ZxEmAzZ6yo22ROkmogzm0RrQRbq0x4VDyF1s0_TLd44nt1OLumxHbI9KJqgyJW0jiXI9E1WGFaiEIvkcthYGTmgSjDJgT65v8rN6dYe7kNqyoE-863lCjGs4yLigHFa-Hp_1uSVMYrwLFcMGpHkNe0K6xP4-V4MbQq3S7OpFHXZ3SXi4WpTsDMg_rLnnru-mrzVsOthj-NhOK1ZzzB7FDwo_xG94cCXBdRkBQpCQZaTD8rU8A7Kw48MRaBiwI9PhxvkellE_MF5tNVNH0BNjxT_msnrrvBZA1bgXSorY4BG1CjGI25k_msBLt805V2AApMq6PTftBLLpxw50jZLpQiJOh34UoRPUcon70auhS2pWoD7vexhbdd0MYXo4y4KfRN_3_cqcQt7j87TQjzgWE-02QA9hAXICCWwqRkmzDivOXSfiKFpM4ITJKAAG0vqKeZctwF4SEc6FvUUuma0Y8YMJSvvm64I-dYkNRVtOq-SgS3LzA-C7azm9iPlsdN_ZSOKCTmH1KWI9vUazpnQKvISV6Xgj70XT8hVNyowl9oVIcSlvDttBKM

### Ajout d'un favoris
POST http://localhost:8000/api/favorite/add/6
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDQzNjM0NjgsImV4cCI6MTcwNDM2NzA2OCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6Im1haWFuYSJ9.M-ZsKY17BxynYwBidc2Zeh2UfnpSxjYXYsCFAoVhVkT_Mj14eW-JW-2rgjbC1VaRXm84xKuk_PNR7Ggf1cJEof7YvCAQuCsiu-C4Muf5itMQOEreII1A_ZxEmAzZ6yo22ROkmogzm0RrQRbq0x4VDyF1s0_TLd44nt1OLumxHbI9KJqgyJW0jiXI9E1WGFaiEIvkcthYGTmgSjDJgT65v8rN6dYe7kNqyoE-863lCjGs4yLigHFa-Hp_1uSVMYrwLFcMGpHkNe0K6xP4-V4MbQq3S7OpFHXZ3SXi4WpTsDMg_rLnnru-mrzVsOthj-NhOK1ZzzB7FDwo_xG94cCXBdRkBQpCQZaTD8rU8A7Kw48MRaBiwI9PhxvkellE_MF5tNVNH0BNjxT_msnrrvBZA1bgXSorY4BG1CjGI25k_msBLt805V2AApMq6PTftBLLpxw50jZLpQiJOh34UoRPUcon70auhS2pWoD7vexhbdd0MYXo4y4KfRN_3_cqcQt7j87TQjzgWE-02QA9hAXICCWwqRkmzDivOXSfiKFpM4ITJKAAG0vqKeZctwF4SEc6FvUUuma0Y8YMJSvvm64I-dYkNRVtOq-SgS3LzA-C7azm9iPlsdN_ZSOKCTmH1KWI9vUazpnQKvISV6Xgj70XT8hVNyowl9oVIcSlvDttBKM