### Connexion API
POST http://localhost:8000/api/login_check
content-type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Deconnexion API
POST http://localhost:8000/api/logout
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk5OTI4ODQsImV4cCI6MTY5OTk5NjQ4NCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.uzYmZaRT35_B7d-jdokwvi_rb0okRNSVzqSmLuzFQQsyvzbBzU7VqELPpZAX-ryTZ7IH1CFvjYzdQoU-6VjdqkTLy8dUQYTnSS91ogfPacQCw23A8ABem5f_XiX7a9EMGnGMs3VL4KMZE9bkwR55RH5j2qdyaEr9zPh1rhHTtgC1WUv82yRo5Ild62Yp67ZCKv_QNPOE6KM8_AOUgZ4-9y3gUcj4RnB3M2-vuj5obhXcXs2aDSRDe4I5LdR1i_uNdVSr2bd8kndnFgpU5klwueywsrc_1HuHNiOUCA1P6wHxJhN3MUuWHyhRU4hwgP_fxcI_vf_3Jnzse1B2rdp6TOLbYrxbVyz2-w3cxjaO9pacL3-WXMuaJ0kP4DrB6YpPxJl6d4pIIzpsvgXX-JO8CMW_XZAxw7fSj967hpF_YUL-WonrNyuVwHvgwuHpSAVT9GgC92W5rDKHNXbu1WkxzHSJttxXWUYFdcR6lv0Wq_Rd-ybqLWrwqJADjTyuPfNXtDzJrR1y-lV1hVRt2TqCWwiRsvy5bYrWA1DNGD8JPP6z9hoX8fXWAhA_B5GbJKWI7hZwhGcZvUXksVJBptrnTyq7nLDaJ7kMOrWvAo3rf3-KAJDYkSiC2VkGWgL6luhFUSI1ZZUagEGzGA-1c3K4-QzLYXlEEIqXz_3CJJ1FbKM

### Connexion au backoffice
POST http://localhost:8000/back/login
content-type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Déconnexion du backoffice
GET http://localhost:8000/back/logout

