### Connexion
POST http://localhost:8000/api/login_check
content-type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Liste des vegetables
GET http://localhost:8000/api/vegetable
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk4NjU4MjcsImV4cCI6MTY5OTg2OTQyNywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.Lqzf_n9abgKJ8As5HwAY5cm__or_zi3FOd39EuiAnoos6KotslhPHzOQ2llSw2_D4XzxXaw1wNayRBGzRyiIkLLW9-M_v4WjodYp2FXxiW6QjREbnd1zXt_hLsbZ_wL3HwULgowPMDsMCzmHp6tTwtw28eq42oS6XuYbVzLSvdBI6PyZBkxUVnCuGI6WzIqEl9xmlW6y5aHViqDtBHIXhP8sW3IbOFktpR2DBAHnac0apJYTGNb6aNwr1Nj1t6uJ3Dka1XQDyMyzG1veGa7VcvqhxsFv0tpZ_pS7VKLzw9-0mnuZo8pvBZOqLwse61UMP0Zozlp01L9ZqJwpiPOunMMzNYFOg4bSEYnpxn8frkL1W4qui8L8P92G2GJBugRbmJuwkfIUoADzG1Ll9z4a92dkvVEgGRGlwm0g9iZGyP7fOvIIhpIclQ-gAzrjay6qkWE2xvg47YcZi71N34qO1gQ31kAgKEy7IL-TYjBF8UXN50M1MmZWmU6HCRHLewxtZs_o9WgB3y1fO_AMvm7IuWNVPLO3cBycUzsMA5NED1XS4KHslQcN1dtoaBs5caysaM1hHwsatMmG82u4OQ78vweUdD-Rbok4zYohsRvDADYwXvcIwP0FmVo5yLhb_gQjNV4RdPvYdVfN9yTvsAAbSSog1xpljnE8weX6TqMmpAU

### Deconnexion
POST http://localhost:8000/logout
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk1Mzc2NjAsImV4cCI6MTY5OTU0MTI2MCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.fyLmUAeoqGECrPp0OEqqaemNzlcL5j0z6z5uUCn7dUokl1KKcX7ECKjGdgIQfORIH_dcWvnKSJK7NqV92ooSNsKRigSH96UCn4EHdmf9VaA21Do5VtCyjzFjqfBG44C3GS82gfDRzJnb-jJjfXXhB2C_CRV_7nZZQ8bV8BRXX9B4NXFgGlPli47c3p4aci2NR_BBqj1QHWGtxR7Kn9FxcPDEiVsFXYU933VHq0B3DTxuydtJb45N02AaP_8qrc7ACNNE_Q7qxSa0XBNln-Ue5djOhqK_PJxbot_gEE55PE_zyTiZF1BNDMIHkiBmg-78MRBKNPQeNPp0tmwhEQU5yw