### Connexion
POST http://localhost:8000/api/login_check
content-type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Liste des vegetables
GET http://localhost:8000/api/member
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk4ODU3MDYsImV4cCI6MTY5OTg4OTMwNiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.c6s88a0rYvITV1x6sTGEqfpcH4N71ikXCdNDmhHSSLObOHONnxgZrq0YEXqDAy1zziR2lkhPCSM2ZVq9XQ4lONEcnzHPje7hWcZJrFk7I5Kyf_p5TB_oExdBIIFmQYxVmGIN6eFfgBFuQV1yDyYPzLPCD5gBE6y1B1trve1gaR8d5SaDr0IuNIjJ6geRYoZMWdz7_WXgn4oSzwesszc86R2Oo_ZBloCfvh3pm99lbufXWnFrfKehYDOqyqJpz0bCjwhKK2HTXU5uvJ56rXQYczP-NA6taIFXkTxSbZMQm0cvgu7aasbShbciXjyp8WlToh1y9v1_4KlW_PId5FAj23D41c4lVYFsa12ER_dyBAzpk-LKHYnD2ymwCHtaXHAI0ro7CYyVOOU2i1F9ZzmaK695ewZmvmwBs7kCpDrSUGK3lbmFCU7rHGQLX7Oz_teM3NMyF9MEXAcSBxzTK5ajwHij2ptQVNAExwgCJ6ygQ6dkk7NoL9JVyuIA6sEcIywif5HBsxs8pjWNrZiwUvKk0Ufa46PaB8CC4v_ZCYgDkxjK4RdTza3C1JA4JpWvNqZ4Z2sfMC3lt3WT0KZfGGvev6sPUxDHCvQUDFtGOltCnwf7-GfBq5fzPiX1IV-NraohFPg2ZJQJjtY8rlvwCMV_3QAgkDEAl6IP54pa2_saNPs

### Deconnexion
POST http://localhost:8000/logout
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk4ODU3MDYsImV4cCI6MTY5OTg4OTMwNiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.c6s88a0rYvITV1x6sTGEqfpcH4N71ikXCdNDmhHSSLObOHONnxgZrq0YEXqDAy1zziR2lkhPCSM2ZVq9XQ4lONEcnzHPje7hWcZJrFk7I5Kyf_p5TB_oExdBIIFmQYxVmGIN6eFfgBFuQV1yDyYPzLPCD5gBE6y1B1trve1gaR8d5SaDr0IuNIjJ6geRYoZMWdz7_WXgn4oSzwesszc86R2Oo_ZBloCfvh3pm99lbufXWnFrfKehYDOqyqJpz0bCjwhKK2HTXU5uvJ56rXQYczP-NA6taIFXkTxSbZMQm0cvgu7aasbShbciXjyp8WlToh1y9v1_4KlW_PId5FAj23D41c4lVYFsa12ER_dyBAzpk-LKHYnD2ymwCHtaXHAI0ro7CYyVOOU2i1F9ZzmaK695ewZmvmwBs7kCpDrSUGK3lbmFCU7rHGQLX7Oz_teM3NMyF9MEXAcSBxzTK5ajwHij2ptQVNAExwgCJ6ygQ6dkk7NoL9JVyuIA6sEcIywif5HBsxs8pjWNrZiwUvKk0Ufa46PaB8CC4v_ZCYgDkxjK4RdTza3C1JA4JpWvNqZ4Z2sfMC3lt3WT0KZfGGvev6sPUxDHCvQUDFtGOltCnwf7-GfBq5fzPiX1IV-NraohFPg2ZJQJjtY8rlvwCMV_3QAgkDEAl6IP54pa2_saNPs