### Liste des member
GET http://localhost:8000/api/member

### Détail d'un member
GET http://localhost:8000/api/member/22
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDAwNTIzNjUsImV4cCI6MTcwMDA1NTk2NSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfTUVNQkVSIl0sInVzZXJuYW1lIjoiYWRtaW4ifQ.kTt3UhjOrT68aZfv0WPnzCwf6geU_E5SVpve6v2-_PckucBrPv6kd5sxJ1TBLJpe4kH6x2jtG3maVOcpw09Bt-I3JbjqG9CZzousEcDw7WaEZop1tilafr5bY-c0YGvBQkzKvhJ6g-xkEbuKImR-t1cR-vUVCxv4D5cbOD7czUEmAFOPx2wpvSA4Nbv595ITyopPJS9U--45tTFamZ1htgUROudMmBftEL-xenT6SvxnsqsbM5wzzFzLPzeA85iU6cOwTSfiM5wghmG_J366U6Qq03DMv5MQvw8L6Y_dIFpwmYcJZU3TZKAHjPT9lmDiX9v4keWLCq9YS-ZIXraY0D_zY0pmum0ieSR6CfF44q2Pt0hSgsBCJ7N2o11P43v5dUiP6XO3czOVn02gcwqTg0Iflh1ghw6PFZ5SYnl2eREJjxQ82ljobGM1o21jnLXW4eZdeF2D6gzdWsl2uHqMQtK2Aw3WnN-x8xAVFVzDuSN8gnTw8z50_D9gvV00ZZubI7k5aMjeafgXS0Ufpz5EY5qWdorX7IHEDs93EbQxO8YA6aS1YJtX4pwdM6cKNnzB7rFe-EmG92I-FT73G4Ax3WSG9etqU0soyEJZzmzgU595zT3-rIbDaj3yDOBdzF-4-24k9w_wqja4yzenjEJOeljrM4cGeZjTwqSPif1RoqM

### Modification d'un member
PUT http://localhost:8000/api/member/3
content-type: application/json

{
    "pseudo" : "moderateur"
}

### Suppression d'un member
DELETE http://localhost:8000/api/member/4

### Ajout d'un member
POST http://localhost:8000/api/member/add
content-type: application/json

{
  "pseudo": "TestApi",
  "password": "abcdefjh",
  "role": "[ROLE_USER]",
  "created_at": "2023-01-01"
}

### Modification d'un member backoffice
PUT http://localhost:8000/back/member/update/3
content-type: application/json

{
    "pseudo" : "moderateur"
}