### Liste des member
GET http://localhost:8000/api/member

### Détail d'un member
GET http://localhost:8000/api/member/20

### Modification d'un member
PUT http://localhost:8000/api/member/3
content-type: application/json

{
    "pseudo" : "moderateur"
}

### Suppression d'un member
DELETE http://localhost:8000/api/member/4

### Ajout d'un member
POST http://localhost:8000/api/member/add
content-type: application/json

{
  "pseudo": "TestApi8",
  "password": "testapi8",
  "created_at": "2023-01-01",
  "email": "coucou3@gmail.com",
  "newsletter": false
}